# Spring Configuration
spring:
  application:
    name: DSS API

vault:
  uri: "http://localhost:8201"
  token: "00000000-0000-0000-0000-000000000000"

#auth-server:
#  internal-domain: "http://localhost:8081"
#  external-domain: "http://localhost:8081"
#  realm: CredentialIssuer

# Server Configuration
server:
  #port: 8088
  # Local port
  port: 8050

# Logging Configuration
logging:
  level:
    es.in2: DEBUG

# Actuator Configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true

# Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method

certificate:
  key-store-password: ""
