# Spring Configuration
spring:
  application:
    name: remote-signature-ms

aca-cross-rmt-sign-ms-uri: "http://localhost:8050"
aca-cross-keycloak-ms-uri: "http://localhost:7001"

# AZURE APP CONFIG
azure:
  app:
    config:
      endpoint: ${APP_CONFIG_ENDPOINT}
      label:
        global: service-discovery

# Server Configuration
server:
  #port: 8088
  # Local port
  port: 8050

# Logging Configuration
logging:
  level:
    org.springframework.security: INFO
    es.in2: DEBUG

# Actuator Configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true

auth-server:
  internal-domain: "http://localhost:8081"
  external-domain: "http://localhost:8081"
  realm: CredentialIssuer

# Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method

openapi:
  server:
    description: Remote signature server
  info:
    title: Remote signature API
    version: 1.0.0-SNAPSHOT
    description: null
    termsOfService: https://example.com/terms-of-service
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    contact:
      email: info@example.com
      name: Example
      url: https://example.com
certificate:
  key-store-path: "classpath:certs/zeus.p12"
  key-store-password: "SAVeJ2Sf"
  key-store-type: "PKCS12"
  cert-alias: "zeus olimpos"
  private-key-password: "SAVeJ2Sf"