trigger: none

variables:
  - name: registryName
    value: 'epudevcr01'
  - name: azureSubscription
    value: 'service-endpoint-bs-tf-deploy-apps-iep-gene-demo-dev'

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    displayName: AZ ACR Login
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az acr login --name $(registryName)'
  - task: SonarCloudPrepare@1
    displayName: "SonarCloud prepare"
    inputs:
      SonarCloud: 'Sonarcloud'
      organization: 'in2gencat'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'in2Gencat_gencat-iep-remote-signature-ms'
      cliProjectName: 'gencat-iep-remote-signature-ms'
      cliSources: './src/main/java'
      extraProperties: 'sonar.java.binaries=$(Build.SourcesDirectory)'
  - script: chmod +x $(Build.SourcesDirectory)/gradlew
    displayName: 'Make gradlew executable'
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build test'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
  - task: SonarCloudAnalyze@1
    displayName: "SonarCloud Analyze"
  - task: SonarCloudPublish@1
    displayName: "SonarCloud publish"
    inputs:
      pollingTimeoutSec: '300'
